name: Cluster Runner

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Google test submodule checkout
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      - name: Setup MPI
        uses: mpi4py/setup-mpi@v1

      - name: CMake setup
        uses: jwlawson/actions-setup-cmake@v1

      - name: Configure build
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Test implementation on github runner
        run: ctest --test-dir build

      - name: Install Singularity dependencies and compile singularity
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake cryptsetup fuse fuse2fs git libfuse-dev  libglib2.0-dev libseccomp-dev libtool pkg-config runc squashfs-tools squashfs-tools-ng uidmap wget zlib1g-dev 

          export VERSION=1.21.6 OS=linux ARCH=amd64
          wget https://dl.google.com/go/go$VERSION.$OS-$ARCH.tar.gz
          sudo tar -C /usr/local -xzvf go$VERSION.$OS-$ARCH.tar.gz
          rm go$VERSION.$OS-$ARCH.tar.gz
          echo 'export GOPATH=${HOME}/go' >> ~/.bashrc
          echo 'export PATH=/usr/local/go/bin:${PATH}:${GOPATH}/bin' >> ~/.bashrc
          source ~/.bashrc

          git clone --recurse-submodules https://github.com/sylabs/singularity.git
          cd singularity && git checkout --recurse-submodules v4.1.0 && ./mconfig && make -C ./builddir && sudo make -C ./builddir install
