name: Cluster Runner

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Google test submodule checkout
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      - name: Setup MPI
        uses: mpi4py/setup-mpi@v1

      - name: CMake setup
        uses: jwlawson/actions-setup-cmake@v1

      - name: Configure build
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Test implementation on github runner
        run: ctest --test-dir build

      - name: Install Singularity dependencies and compile singularity
        run: sudo apt install singularity-ce

      - name: Build singularity image
        run: sudo singularity build main.sif Singularity.def
