name: Cluster Runner

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Google test submodule checkout
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive
      - name: Setup MPI
        uses: mpi4py/setup-mpi@v1

      - name: CMake setup
        uses: jwlawson/actions-setup-cmake@v1

      - name: Configure build
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Test implementation on github runner
        run: ctest --test-dir build

      - name: Install Singularity dependencies and compile singularity
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake cryptsetup fuse fuse2fs git libfuse-dev libglib2.0-dev libseccomp-dev libtool pkg-config runc squashfs-tools squashfs-tools-ng uidmap wget zlib1g-dev 
          wget https://github.com/sylabs/singularity/releases/download/v4.1.3/singularity-ce_4.1.3-focal_amd64.deb
          sudo dpkg -i singularity-ce_4.1.3-focal_amd64.deb
      - name: Build singularity image
        run: sudo singularity build main.sif Singularity.def

      - name: Copy singularity image and run on the Galileo cluster using the secrets
        env:
          ssh_usr: ${{ secrets.SUPER_SECRET_USERNAME }}
          ssh_pwd: ${{ secrets.SUPER_SECRET_PLEASE_DO_NOT_TRY_TO_LOOK }}
        run: |
          sshpass -p "$ssh_pwd" -v scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null main.sif job.sh matrixA.txt matrixB.txt $ssh_usr@login.g100.cineca.it:~
          sshpass -p "$ssh_pwd" -v ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $ssh_usr@login.g100.cineca.it sbatch job.sh
          sleep 10s
          sshpass -p "$ssh_pwd" -v scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $ssh_usr@login.g100.cineca.it:~/matmul.out result.out
          sshpass -p "$ssh_pwd" -v scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $ssh_usr@login.g100.cineca.it:~/error.out error.out

      - name: Upload matmul results
        uses: actions/upload-artifact@v4.3.3
        with:
          name: result
          path: result.out

      - name: Upload Error log
        uses: actions/upload-artifact@v4.3.3
        with:
          name: error
          path: error.out
